const { spawn } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const root = path.join(__dirname, '..');
const packaged = process.argv.includes('--packaged');
if (!packaged && !fs.existsSync(path.join(root, '.env'))) fs.copyFileSync(path.join(root, '.env.example'), path.join(root, '.env'), fs.constants.COPYFILE_EXCL);
const environment = { ...process.env };
delete environment.ELECTRON_RUN_AS_NODE;
const executable = packaged ? path.join(root, 'dist', 'WordBridge-win32-x64', 'WordBridge.exe') : require('electron');
const args = process.argv.slice(2).filter(arg => arg !== '--packaged');
const child = spawn(executable, [...(packaged ? [] : [root]), ...args], { cwd: root, stdio: 'inherit', env: environment, windowsHide: true });
child.on('error', error => { console.error(error.message); process.exitCode = 1; });
child.on('exit', code => { process.exitCode = code ?? 1; });
